{{- if .Values.externalSecrets.enabled }}
{{- if and .Values.auth.vault.enabled .Values.auth.vault.secretProviderClassName }}
{{- fail "Cannot enable both externalSecrets and auth.vault. Please choose one." }}
{{- end }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ default (include "jellycat-ui.fullname" .) .Values.externalSecrets.name }}
  labels:
    app.kubernetes.io/name: {{ include "jellycat-ui.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "jellycat-ui.chart" . }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name | required "externalSecrets.secretStoreRef.name is required when externalSecrets.enabled=true" }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind | default "ClusterSecretStore" }}
  target:
    name: {{ default .Values.auth.vault.secretName .Values.externalSecrets.secretName | default (printf "%s-auth" (include "jellycat-ui.fullname" .)) }}
    creationPolicy: Owner
  data:
    # Auth / Authentik OAuth2 secrets
    - secretKey: {{ .Values.externalSecrets.data.clientSecretKey | default "clientSecret" }}
      remoteRef:
        key: {{ required "externalSecrets.remoteRef.basePath is required when externalSecrets.enabled=true" .Values.externalSecrets.remoteRef.basePath }}
        property: {{ .Values.externalSecrets.data.clientSecretKey | default "clientSecret" }}
    # Database URL
    - secretKey: {{ .Values.externalSecrets.data.databaseUrlKey | default "DATABASE_URL" }}
      remoteRef:
        key: {{ required "externalSecrets.remoteRef.basePath is required when externalSecrets.enabled=true" .Values.externalSecrets.remoteRef.basePath }}
        property: {{ .Values.externalSecrets.data.databaseUrlKey | default "DATABASE_URL" }}
    # ClickHouse
    - secretKey: {{ .Values.externalSecrets.data.clickhouseAddrKey | default "CLICKHOUSE_ADDR" }}
      remoteRef:
        key: {{ required "externalSecrets.remoteRef.basePath is required when externalSecrets.enabled=true" .Values.externalSecrets.remoteRef.basePath }}
        property: {{ .Values.externalSecrets.data.clickhouseAddrKey | default "CLICKHOUSE_ADDR" }}
    - secretKey: {{ .Values.externalSecrets.data.clickhouseDbKey | default "CLICKHOUSE_DB" }}
      remoteRef:
        key: {{ required "externalSecrets.remoteRef.basePath is required when externalSecrets.enabled=true" .Values.externalSecrets.remoteRef.basePath }}
        property: {{ .Values.externalSecrets.data.clickhouseDbKey | default "CLICKHOUSE_DB" }}
    - secretKey: {{ .Values.externalSecrets.data.clickhouseUserKey | default "CLICKHOUSE_USER" }}
      remoteRef:
        key: {{ required "externalSecrets.remoteRef.basePath is required when externalSecrets.enabled=true" .Values.externalSecrets.remoteRef.basePath }}
        property: {{ .Values.externalSecrets.data.clickhouseUserKey | default "CLICKHOUSE_USER" }}
    - secretKey: {{ .Values.externalSecrets.data.clickhousePasswordKey | default "CLICKHOUSE_PASSWORD" }}
      remoteRef:
        key: {{ required "externalSecrets.remoteRef.basePath is required when externalSecrets.enabled=true" .Values.externalSecrets.remoteRef.basePath }}
        property: {{ .Values.externalSecrets.data.clickhousePasswordKey | default "CLICKHOUSE_PASSWORD" }}
    # NATS
    - secretKey: {{ .Values.externalSecrets.data.natsUrlKey | default "NATS_URL" }}
      remoteRef:
        key: {{ required "externalSecrets.remoteRef.basePath is required when externalSecrets.enabled=true" .Values.externalSecrets.remoteRef.basePath }}
        property: {{ .Values.externalSecrets.data.natsUrlKey | default "NATS_URL" }}
    - secretKey: {{ .Values.externalSecrets.data.natsSubjectKey | default "NATS_SUBJECT" }}
      remoteRef:
        key: {{ required "externalSecrets.remoteRef.basePath is required when externalSecrets.enabled=true" .Values.externalSecrets.remoteRef.basePath }}
        property: {{ .Values.externalSecrets.data.natsSubjectKey | default "NATS_SUBJECT" }}
    - secretKey: {{ .Values.externalSecrets.data.natsUsernameKey | default "NATS_USERNAME" }}
      remoteRef:
        key: {{ required "externalSecrets.remoteRef.basePath is required when externalSecrets.enabled=true" .Values.externalSecrets.remoteRef.basePath }}
        property: {{ .Values.externalSecrets.data.natsUsernameKey | default "NATS_USERNAME" }}
    - secretKey: {{ .Values.externalSecrets.data.natsPasswordKey | default "NATS_PASSWORD" }}
      remoteRef:
        key: {{ required "externalSecrets.remoteRef.basePath is required when externalSecrets.enabled=true" .Values.externalSecrets.remoteRef.basePath }}
        property: {{ .Values.externalSecrets.data.natsPasswordKey | default "NATS_PASSWORD" }}
    - secretKey: {{ .Values.externalSecrets.data.natsCredsKey | default "NATS_CREDS" }}
      remoteRef:
        key: {{ required "externalSecrets.remoteRef.basePath is required when externalSecrets.enabled=true" .Values.externalSecrets.remoteRef.basePath }}
        property: {{ .Values.externalSecrets.data.natsCredsKey | default "NATS_CREDS" }}
{{- end }}
