{{- if and .Values.auth.vault.enabled .Values.auth.vault.secretProviderClassName }}
{{- if .Values.externalSecrets.enabled }}
{{- fail "Cannot enable both externalSecrets and auth.vault. Please choose one." }}
{{- end }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.auth.vault.secretProviderClassName | required "auth.vault.secretProviderClassName is required when auth.vault.enabled=true" }}
  labels:
    app.kubernetes.io/name: {{ include "jellycat-ui.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "jellycat-ui.chart" . }}
spec:
{{- if .Values.auth.vault.spec }}
{{ tpl (toYaml .Values.auth.vault.spec) . | nindent 2 }}
{{- else }}
  # Provide raw SecretProviderClass spec in values at auth.vault.spec
  # Example for Vault provider:
  # provider: vault
  # parameters:
  #   vaultAddress: https://vault.example.com
  #   roleName: my-role
  #   objects: |
  #     - objectName: ui-auth-secrets
  #       secretPath: secret/data/jellycat/ui
  #       secretKey: ""
  # secretObjects:
  #   - secretName: {{ default (printf "%s-auth" (include "jellycat-ui.fullname" .)) .Values.auth.vault.secretName }}
  #     type: Opaque
  #     data:
  #       - key: {{ .Values.auth.vault.keys.clientSecret }}
  #         objectName: clientSecret
  #       - key: {{ .Values.auth.vault.keys.nextAuthSecret }}
  #         objectName: NEXTAUTH_SECRET
{{- end }}
{{- end }}
